### PR TITLE
ACM at UCLA --> ACM chapter at UCLA on all pages.

### PR DESCRIPTION
**Pull request by dtjanaka**

### CODE REVIEW

**Review by matthewcn56 — CHANGES_REQUESTED** [review]
Thanks for helping facilitate the ACM at UCLA --> ACM chapter at UCLA rebranding!

IMO, it doesn't hurt to update the alt text to reflect this change as well, and there's some extra spots like within the readme where this can be addressed as well.

While not everyone sees these sections of the site or our repository, it might help solidify the change of name.

**Comment by dtjanaka** [comment]
> Thanks for helping facilitate the ACM at UCLA --> ACM chapter at UCLA rebranding!
> 
> IMO, it doesn't hurt to update the alt text to reflect this change as well, and there's some extra spots like within the readme where this can be addressed as well.
> 
> While not everyone sees these sections of the site or our repository, it might help solidify the change of name.

I made a second PR addressing this. Readme was adjusted, alt texts were not when they were describing *exactly* what an image shows.

**Comment by dtjanaka** [comment]
https://github.com/uclaacm/website/pull/473

**Comment by matthewcn56** [comment]
> #473

Sounds good, we can merge in #472 once #473 gets merged since it looks like 473 is trying to merge that branch into this branch

**Comment by mattxwang** [comment]
Similar comment as #473 - 

> Wait sorry, can we ... *not* do this yet? I'm looking to meet w/ the ACM to renegotiate the branding guidelines, and as of now our website is compliant with what they've asked.

**Pull request closed without merging**
