### PR TITLE
Fix article image size on mobile response

### PR DESCRIPTION
**Pull request by vohndernet**
Quick fix of an issue where article images are too large and distorts website sizing on mobile. Can one of you approve, @chern @austinkeil ?

### CODE REVIEW

**Review by chern — COMMENTED** [review]
Thanks for jumping on this, Nhi! Using the responsive viewers on Safari and Chrome, looks like it seems to be resolved for most mobile screens; however, some of the wider phone screens still seem to have off-center alignment for the news items:

Safari:
Screen Shot 2020-09-17 at 1 24 06 AM

Chrome:
Screen Shot 2020-09-17 at 1 23 51 AM

**Comment by vohndernet** [comment]
Adjusted for wider-screens now! Here's screenshot confirmation:
Chrome:
image

Safari:
image

**Review by austinkeil — APPROVED** [review]
Easy enough haha

**Review by chern — APPROVED** [review]
Looks good, Nhi! Thanks a bunch!

**Pull request merged**
