### PR TITLE
Update carousel etc

### PR DESCRIPTION
**Pull request by MiraynaMckinney**
Start Updating Carousel Images

### CODE REVIEW

**Review by reginawang3495 — APPROVED** [review]
lgtm!!

@advaithg I wonder if we should have data on alts for each image (maybe a separate ticket)

**Comment by advaithg** [comment]
> @advaithg I wonder if we should have data on alts for each image (maybe a separate ticket)

I don't think so, since 
- these images are purely decorative
- they are moving, so alt text might be needlessly confusing

I think having `alt=""` to mark as decorative works.

**Review by advaithg — COMMENTED** [review]
hmm it looks like `about2.png` will probably have to be manually rotated or angled (as `about1.png` was) so it looks upright in the website

**Review by advaithg — COMMENTED** [review]
Hi @MiraynaMckinney , just checking to see if you're still working on this PR!

**Pull request closed without merging**
