### PR TITLE
Updates react-scripts to v4, eslint to v7

### LINKED ISSUE #136: Update react-scripts (CRA) to v4
Linked to #130.

This will have to be a semi-manual change!

### PR DESCRIPTION
**Pull request by mattxwang**
This PR does a couple of things:

* update `react-scripts` (the package for create-react-app) to `v4.0.3` - this is a major breaking change, but also helps with #130 
* update `eslint` to v7+, to resolve newly-created peer-dependency mismatches 
* removes some unused CSS I forgot to remove from #148 
* changes the about diamond to a `src/assets`-imported image rather than using a `background-image` hack (the nice externality is that it's also more accessible)!

Closes #136.

### CODE REVIEW

**Comment by mattxwang** [comment]
As a note, we're failing a CI error from an issue with sass not resolving images in the public loader. This is an open issue on the CRA repo, and *I don't want to bundle the image into our stylesheet if possible*.

https://github.com/facebook/create-react-app/issues/10022

**Review by evanzhong — APPROVED** [review]
on the most part lgtm.

Things I note:
- Merge conflict on `package-lock.json` is pretty gnarly, can just force push if you want as you listed in PR description.
-  Personally I'm not opposed to just bundling the image if it's just this one reference to background image.
- Obviously failing integration tests not ideal but from discussions you linked fix does not seem that bad (moving from `public` to `src` folders)

**Comment by mattxwang** [comment]
Update - turns out our icons also use this pathing 😢 . I'll update them first, then circle back.

**Comment by mattxwang** [comment]
Hm, I am ... messing up this force-merge. Sorry for the notifs Evan, will re-push.

**Pull request merged**
