### PR TITLE
updated covid policies s22

### LINKED ISSUE #457: Update ACM COVID Policies page with Spring Quarter changes
Changes requested to [https://acm.cs.ucla.edu/covid](https://acm.cs.ucla.edu/covid)

image

Change ` ACM at UCLA COVID Policies Winter 2022` to ACM at UCLA COVID Policy Spring 2022. 

Change [UCLA's return to campus](https://covid-19.ucla.edu/ucla-return-to-campus/) to [UCLA's COVID-19 Protocols](https://covid-19.ucla.edu/ucla-covid-protocols/)

Change `Last Major Update:` to Sunday, March 27th, 2022 

Add a bullet point to `Version history `with date Sunday, March 27th, 2022  and the following copy:
`Updated based on UCLA's COVID-19 protocol updates for spring quarter`

image

Update embedded google doc and `Link to Google Doc` to point to 
[https://docs.google.com/document/d/1IcBZ4yj4kJ14Gg0PVw3xbg-QqRYUQGUlHm8vVskgQOQ/edit?usp=sharing](https://docs.google.com/document/d/1IcBZ4yj4kJ14Gg0PVw3xbg-QqRYUQGUlHm8vVskgQOQ/edit?usp=sharing)

Download ACM at UCLA COVID Policy Spring 2022 as PDF and update the `Link to PDF` button to point to this new PDF.

### PR DESCRIPTION
**Pull request by matthewcn56**
Updates covid protocol information as necessary for Spring 2022.
Closes #457.

### CODE REVIEW

**Review by advaithg — APPROVED** [review]
looks good!

**Comment by advaithg** [comment]
only change I can think of is updating the banner to point to the covid policies, but I don't know if that's required - upto PVP!

**Comment by matthewcn56** [comment]
> only change I can think of is updating the banner to point to the covid policies, but I don't know if that's required - upto PVP!

Which banner in particular do you think should point to the covid policies? And I think that can be a separate PR as this one just updates the policies itself.

Maybe that can be a separate PR?

**Comment by advaithg** [comment]
the banner on the homepage!

**Pull request merged**
