### PR TITLE
resolves axe errors in #247

### PR DESCRIPTION
**Pull request by VeeGee-Creations**
### Resolve Secondary Font Color Contrast

variables.scss:
* font-secondary-color: #777 fails contrast on most text sizes with a contrast of 4.47:1 on white background
* darkened font-secondary-color: #595959 passes all text sizes with a contrast of 7:1 on white background

### Resolve `<ul>` Nesting

Navbar.js:
* wrapped .committee-mobile-nav in `<li>`
* gave `<li>` id committee-mobile-nav-item

Navbar.scss:
* targeted #committee-movile-nav-item to fit height to content

### Resolve Landmark Error

Layout.js:
* added 'main' role to .main-container

Navbar.js:
* added 'banner' role to #navbar
* added 'navigation role to #desktop-nav and #hamburger-menu

### CODE REVIEW

**Comment by mattxwang** [comment]
Hi Vincent,

Thank you for submitting this PR! Wanted to let you know that it's on our radar, and we'll try to get it reviewed later today/tomorrow.

**Comment by VeeGee-Creations** [comment]
Thank you. There is also the option of using HTML5 landmark tags if you prefer. I used roles as a less intrusive change but am willing to switch approach.

**Review by mattxwang — APPROVED** [review]
Had a chance to take a look, and all of these are positive improvements! LGTM.

Thank you for your contribution @VeeGee-Creations! If you don't mind me asking, how'd you find out about our project?

**Comment by VeeGee-Creations** [comment]
I finished my fullstack bootcamp last month and was looking for an open source project to participate in. I was scrolling through good first issue tags when I stumbled across your react project. I love working in react and liked idea of lending a hand to a group that will ultimately help others follow their passions

**Comment by mattxwang** [comment]
> I finished my fullstack bootcamp last month and was looking for an open source project to participate in. I was scrolling through good first issue tags when I stumbled across your react project. I love working in react and liked idea of lending a hand to a group that will ultimately help others follow their passions

Ah, gotcha. Congratulations on finishing your Bootcamp, that's awesome! Hopefully you find more open-source work (either with us, or otherwise) where you find a great community 😊 and let us know if there's anything we can do to help out!

**Pull request merged**
