### PR TITLE
docs: adding notes for developers on prod deploy, licensing, and minor corrections

### LINKED ISSUE #187: document CI/CD and Next.js quirks
The current README is incomplete, with a TODO in the place of "Production Deploy"

To fix this, write documentation for the new CI/CD pipeline, and also describe some of the weird quirks with next.js for future devs (mainly `next/image`)

### PR DESCRIPTION
**Pull request by mattxwang**
I want to preface this by saying that I'm planning on rescoping #187 and adding a follow-up issue.

In this PR, I address parts of the original spirit of #187:

* documenting the prod CD pipeline
* updating relevant portions of the docs to be *more correct*
* adding a licensing/attribution section
* adds TOC

I want to move the discussion around Next.js, as well as the general design choices, to a project design document not unlike the one for [Creative Lab's website](https://github.com/UCLA-Creative-Labs/sunshine/blob/master/DESIGN_GUIDELINES.md). More in #202.

closes #187.

### CODE REVIEW

**Comment by mattxwang** [comment]
Eventually, I'd love to see us write something like [this DESIGN_GUIDELINES.md](https://github.com/UCLA-Creative-Labs/tinycl/blob/main/DESIGN_GUIDELINES.md) that Creative Labs has used for their tinycl project!

**Review by evanzhong — APPROVED** [review]
lgtm.

Quickly scanned through the MPL and curious why you think it's a good fit

**Comment by mattxwang** [comment]
> Quickly scanned through the MPL and curious why you think it's a good fit

I didn't make the decision! Nikhil Kansal chose it when he made the repo about four years ago, and I'm extremely wary of relicensing code unless it's absolutely needed. Also, I think a more aggressive copyleft license is *probably* fine for our use-case, I can't imagine it's too restrictive given the general nature of our codebase (not much reusability). 

That being said, open to discussion re: this point - this is a good time to change the license if any.

**Comment by evanzhong** [comment]
> > Quickly scanned through the MPL and curious why you think it's a good fit
> 
> I didn't make the decision! Nikhil Kansal chose it when he made the repo about four years ago, and I'm extremely wary of relicensing code unless it's absolutely needed. Also, I think a more aggressive copyleft license is _probably_ fine for our use-case, I can't imagine it's too restrictive given the general nature of our codebase (not much reusability).
> 
> That being said, open to discussion re: this point - this is a good time to change the license if any.

Personally I think a more aggressive copyleft is appropriate; our branding is unique and out website reflects that. I hear you about not wanting to relicense code though.

**Comment by mattxwang** [comment]
Wrapped up our license convo offline; looks like we'll merge!

**Pull request merged**
