### PR TITLE
Update `committees.js` for NSO Tabling

### LINKED ISSUE #180: Clean up `committees.js`
Now that it's summer, I think we should do something to make `committees.js` less overwhelming (in anticipation of NSO tabling).

In particular, some things to do:

* do we want to keep all the spring events here? if so, should we make it clear?
* if we don't want to keep the spring events, what do we put here instead? 
* images should have `alt` tags! no exceptions, unless you label it as a decorative image!

### PR DESCRIPTION
**Pull request by advaithg**
Resolves #180 

Replaces "Events and Projects" with "Past Events and Projects"
Adds alt tag to every image that doesn't have one, and a general alt for events with no images that use the base committee motif.

### CODE REVIEW

**Comment by mattxwang** [comment]
What are our thoughts on disabling the events section altogether; I'm concerned that this is still information overload.

**Comment by annaguo1012** [comment]
I feel like there is too much information on it right now, but just having the general committee descriptions would be a little vague. What if we kept 3 events/projects for each subcommittee? I feel like they really help give people a better sense of what each committee does and how they could get involved.

**Review by annaguo1012 — COMMENTED** [review]
I know we might do some more changes, but mostly everything looks good to me! There are a few warnings though to use Image from 'next/image' instead of . Do we want to go with that or keep using ? It says Next.js' image component has better performance and automatic image optimization. It also still does lazy-loading by default.

**Comment by advaithg** [comment]
> What are our thoughts on disabling the events section altogether; I'm concerned that this is still information overload.

@mattxwang I think we can go with @annaguo1012 idea, and keep 3 events/projects per committee instead of keeping all of them. I'm kind of concerned about completely disabling events, since that means there's no tangible examples of what each committee does.

**Comment by advaithg** [comment]
> I know we might do some more changes, but mostly everything looks good to me! There are a few warnings though to use Image from 'next/image' instead of . Do we want to go with that or keep using ? It says Next.js' image component has better performance and automatic image optimization. It also still does lazy-loading by default.

The reason we use `` instead of `/next/image` is because `/next/image` has issues when deploying on netlify and when it's applied on SVGs, so throughout the entire codebase - all the PNGs use `/next/image`, but we're stuck with `img` for the SVGs, which include the committee logos and some other images.

**Comment by mattxwang** [comment]
Sounds good, I'll let you and Anna work on this then - great idea @annaguo1012!

**Comment by mattxwang** [comment]
> There are a few warnings though to use Image from 'next/image' instead of 

If this makes code review hard, we can disable the rule just for the lines that trigger the warning, and TODO removing them + link them to #188!

**Review by annaguo1012 — APPROVED** [review]
LGTM!

**Comment by mattxwang** [comment]
Just wanted to check, is this the correct image for JS Chats?

Screen Shot 2021-07-25 at 3 51 37 PM

**Comment by annaguo1012** [comment]
Oh no, that's not the right one. Sorry for not catching that! I can fix it now.

**Pull request merged**
