### PR TITLE
change banner to point to officer apps

### PR DESCRIPTION
**Pull request by advaithg**
Updates website to reflect officer applications for S22!

### CODE REVIEW

**Comment by mattxwang** [comment]
Do you want to change the "join us" page as well?

**Comment by matthewcn56** [comment]
> Do you want to change the "join us" page as well?

Maybe instead of changing the join us page, we can just change the link that the `join us` points to within the navbar instead?

**Review by advaithg — COMMENTED** [review]
Oh yeah I will also update the internship page to mention the officer apps, since we have a place for that on that page too.

**Comment by advaithg** [comment]
> Maybe instead of changing the join us page, we can just change the link that the `join us` points to within the navbar instead?

will check with Ava on this! @avaasmani

**Comment by matthewcn56** [comment]
@advaithg on the join us page, maybe the headline on the top that says that some committees are recruiting can contain a link to the Apply Now card lower down in the page or directly to the application? As is, it can be a bit hard for people to find where the application is without scrolling down.

**Review by matthewcn56 — APPROVED** [review]
Lgtm, thanks for adjusting the info to point to our officer apps! Up to you if you want to wait for ava to take a looksie at it too before merging in.

**Comment by avaasmani** [comment]
Yeah we will keep the join us page pointing to the internship page, the banner looks good!

**Pull request merged**
